Repository spinnaker/kayenta, pull requests merged in 2018-07, with the labels that each got.

#343 fix(judge): Handle tied ranks by adding Gaussian white noise
  kayenta-judge/kayenta-judge.gradle
  kayenta-judge/src/main/scala/com/netflix/kayenta/judge/classifiers/metric/MannWhitneyClassifier.scala
  kayenta-judge/src/main/scala/com/netflix/kayenta/judge/preprocessing/Transforms.scala
  kayenta-judge/src/main/scala/com/netflix/kayenta/judge/utils/RandomUtils.scala
  kayenta-judge/src/test/scala/com/netflix/kayenta/judge/ClassifierSuite.scala
  kayenta-judge/src/test/scala/com/netflix/kayenta/judge/TransformSuite.scala
  kayenta-judge/src/test/scala/com/netflix/kayenta/judge/UtilsSuite.scala
Labels: bug

#344 fix(metrics): NaN pad all metrics properly if we know the start/end/step values.
  kayenta-atlas/src/main/java/com/netflix/kayenta/atlas/metrics/AtlasMetricsService.java
  kayenta-core/src/main/java/com/netflix/kayenta/metrics/MetricSet.java
  kayenta-core/src/main/java/com/netflix/kayenta/metrics/MetricSetMixerService.java
  kayenta-core/src/test/groovy/com/netflix/kayenta/metrics/MetricSetMixerServiceSpec.groovy
  kayenta-datadog/src/main/java/com/netflix/kayenta/datadog/metrics/DatadogMetricsService.java
  kayenta-influxdb/src/main/java/com/netflix/kayenta/influxdb/metrics/InfluxDbMetricsService.java
  kayenta-prometheus/src/main/java/com/netflix/kayenta/prometheus/metrics/PrometheusMetricsService.java
  kayenta-stackdriver/src/main/java/com/netflix/kayenta/stackdriver/metrics/StackdriverMetricsService.java
Labels: bug

#351 fix(judge): Round the Summary Score to 2 decimal places
  kayenta-judge/src/main/scala/com/netflix/kayenta/judge/scorers/WeightedSumScorer.scala
  kayenta-judge/src/test/scala/com/netflix/kayenta/judge/ScorerSuite.scala
Labels: bug

#350 chore(metric-source): Refator to make metric sources fully modular
  kayenta-atlas/src/main/java/com/netflix/kayenta/atlas/controllers/AtlasFetchController.java
  kayenta-atlas/src/main/java/com/netflix/kayenta/atlas/metrics/AtlasMetricsService.java
  kayenta-atlas/src/main/java/com/netflix/kayenta/canary/providers/metrics/AtlasCanaryMetricSetQueryConfig.java
  kayenta-atlas/src/test/java/com/netflix/kayenta/atlas/BackendsTest.java
  kayenta-atlas/src/test/java/com/netflix/kayenta/atlas/IntegrationTest.java
  kayenta-core/src/main/java/com/netflix/kayenta/canary/CanaryMetricSetQueryConfig.java
  kayenta-core/src/main/java/com/netflix/kayenta/canary/ExecutionMapper.java
  kayenta-core/src/main/java/com/netflix/kayenta/canary/providers/metrics/QueryConfigUtils.java
  kayenta-core/src/main/java/com/netflix/kayenta/config/KayentaConfiguration.java
  kayenta-core/src/main/java/com/netflix/kayenta/retrofit/config/RetrofitClientConfiguration.java
  kayenta-core/src/main/java/com/netflix/kayenta/retrofit/config/RetrofitClientFactory.java
  kayenta-core/src/test/groovy/com/netflix/kayenta/canary/providers/QueryConfigUtilsSpec.groovy
  kayenta-core/src/test/groovy/com/netflix/kayenta/metrics/CanaryScopeSpec.groovy
  kayenta-datadog/src/main/java/com/netflix/kayenta/canary/providers/metrics/DatadogCanaryMetricSetQueryConfig.java
  kayenta-datadog/src/main/java/com/netflix/kayenta/datadog/canary/DatadogCanaryScopeFactory.java
  kayenta-datadog/src/main/java/com/netflix/kayenta/datadog/controller/DatadogFetchController.java
  kayenta-datadog/src/main/java/com/netflix/kayenta/datadog/metrics/DatadogMetricsService.java
  kayenta-google/src/main/java/com/netflix/kayenta/google/security/GoogleNamedAccountCredentials.java
  kayenta-influxdb/src/main/java/com/netflix/kayenta/canary/providers/metrics/InfluxdbCanaryMetricSetQueryConfig.java
  kayenta-influxdb/src/main/java/com/netflix/kayenta/influxdb/canary/InfluxDbCanaryScopeFactory.java
  kayenta-influxdb/src/main/java/com/netflix/kayenta/influxdb/controller/InfluxDbFetchController.java
  kayenta-influxdb/src/main/java/com/netflix/kayenta/influxdb/metrics/InfluxDbMetricsService.java
  kayenta-influxdb/src/main/java/com/netflix/kayenta/influxdb/metrics/InfluxDbQueryBuilder.java
  kayenta-influxdb/src/main/java/com/netflix/kayenta/influxdb/security/InfluxDbNamedAccountCredentials.java
  kayenta-influxdb/src/test/java/com/netflix/kayenta/influxdb/service/InfluxdbQueryBuilderTest.java
  kayenta-prometheus/src/main/java/com/netflix/kayenta/canary/providers/metrics/PrometheusCanaryMetricSetQueryConfig.java
  kayenta-prometheus/src/main/java/com/netflix/kayenta/prometheus/controllers/PrometheusFetchController.java
  kayenta-prometheus/src/main/java/com/netflix/kayenta/prometheus/metrics/PrometheusMetricsService.java
  kayenta-stackdriver/src/main/java/com/netflix/kayenta/canary/providers/metrics/StackdriverCanaryMetricSetQueryConfig.java
  kayenta-stackdriver/src/main/java/com/netflix/kayenta/stackdriver/canary/StackdriverCanaryScopeFactory.java
  kayenta-stackdriver/src/main/java/com/netflix/kayenta/stackdriver/controllers/StackdriverFetchController.java
  kayenta-stackdriver/src/main/java/com/netflix/kayenta/stackdriver/metrics/StackdriverMetricsService.java
  kayenta-stackdriver/src/test/groovy/com/netflix/kayenta/providers/metrics/StackdriverCanaryMetricSetQueryConfigSpec.groovy
  kayenta-web/src/main/java/com/netflix/kayenta/Main.java
  kayenta-web/src/main/java/com/netflix/kayenta/config/WebConfiguration.java
Labels: chore

#356 feat(judge): Add Effect Size (Mean Ratio) Check
  kayenta-judge/src/main/scala/com/netflix/kayenta/judge/NetflixACAJudge.scala
  kayenta-judge/src/main/scala/com/netflix/kayenta/judge/classifiers/metric/BaseMetricClassifier.scala
  kayenta-judge/src/main/scala/com/netflix/kayenta/judge/classifiers/metric/MannWhitneyClassifier.scala
  kayenta-judge/src/main/scala/com/netflix/kayenta/judge/classifiers/metric/MeanInequalityClassifier.scala
  kayenta-judge/src/main/scala/com/netflix/kayenta/judge/classifiers/metric/RandomClassifier.scala
  kayenta-judge/src/main/scala/com/netflix/kayenta/judge/stats/DescriptiveStatistics.scala
  kayenta-judge/src/main/scala/com/netflix/kayenta/judge/stats/EffectSizes.scala
  kayenta-judge/src/main/scala/com/netflix/kayenta/judge/utils/MapUtils.scala
  kayenta-judge/src/test/scala/com/netflix/kayenta/judge/ClassifierSuite.scala
  kayenta-judge/src/test/scala/com/netflix/kayenta/judge/StatisticSuite.scala
Labels: enhancement
